#!/bin/bash

for d in ./*; do
	if [ -d "$d" ]; then
		cd "$d"
		pwd
		for f in ./s*.svg; do
			mv "${f}" "${f}.old" 
			inkscape --export-text-to-path --export-filename "${f}" "${f}.old"
			rm "${f}.old"
			echo "${f}"
		done
		cd ..
	fi
done
